[package]
name = "rawst"
version = "0.4.0"
authors = ["Faseeh Shahzad"]
description = "Snag your files efficiently with Rawst downloader"
repository = "https://github.com/Jupiee/rawst"
license = "GPL-3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
codegen-units = 1
lto= "fat"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.38"
clap = {version = "4.5.20", features = ["cargo"]}
directories = "5.0.1"
futures = "0.3.31"
indicatif = "0.17.8"
reqwest = {version= "0.12.9", default-features = false, features = ["stream", "rustls-tls"]}
serde = {version= "1.0.214", features = ["derive"]}
serde_json = "1.0.132"
tokio = {version= "1.41.0", features = ["full"]}
toml = "0.8.19"
