# Run clippy
#
# https://doc.rust-lang.org/clippy/continuous_integration/github_actions.html

name: Clippy check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"


jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          # - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Switch to rust nightly
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
