name: Build and Upload Binaries

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    name: "Build and Upload Binaries"
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install stable Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Upload binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          target: ${{ matrix.target }}
          bin: rawst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
