# Run clippy
#
# https://doc.rust-lang.org/cargo/guide/continuous-integration.html

name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always


jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          # - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Switch to rust nightly
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose --all-targets --keep-going
      - name: Test
        run: cargo test --verbose --all-targets --no-fail-fast
